### ISSUE TITLE
EthereumService.py not able to find Account 

### ISSUE THREAD

**Issue by dabidgs3** [seed-labs/seed-emulator#120]
= Emulator: configureing EthereumService...
==== EthereumServiceLayer: eth_state folder "./eth-states" already exist, overriding.
==== EthereumServiceLayer: looking for binding for eth1...
==== EthereumServiceLayer: configuring as151/host_1 as an eth node...
==== EthereumServiceLayer: adding as151/host_1 as consensus-POW bootnode...
==== EthereumServiceLayer: creating eth account...
Traceback (most recent call last):
  File "blockchain.py", line 28, in <module>
    emu.render()
  File "seed-emulator/seedemu/core/Emulator.py", line 363, in render
    self.__render(layerName, False, True)
  File "seed-emulator/seedemu/core/Emulator.py", line 152, in __render
    layer.configure(self)
  File "seed-emulator/seedemu/services/EthereumService.py", line 956, in configure
    super().configure(emulator)
  File "seed-emulator/seedemu/core/Service.py", line 122, in configure
    self.__configureServer(server, pnode)
  File "seed-emulator/seedemu/core/Service.py", line 92, in __configureServer
    self._doConfigure(node, server)
  File "seed-emulator/seedemu/services/EthereumService.py", line 940, in _doConfigure
    server._createAccounts(self)
  File "seed-emulator/seedemu/services/EthereumService.py", line 796, in _createAccounts
    account = EthAccount(alloc_balance=balance,password=password, keyfilePath=keyfilePath)
  File "seed-emulator/seedemu/services/EthereumService.py", line 251, in __init__
    from eth_account import Account
ModuleNotFoundError: No module named 'eth_account'

**Comment by wonkr** [comment]
The error occurs because you don't have `eth_account` python module.
Please install the `eth_account` module before running it. 
`pip3 install eth_account`
