### ISSUE TITLE
New Release Error [5125ccf..95860ae  master] on mini-internet - blockchain

### ISSUE THREAD

**Issue by dabidgs3** [seed-labs/seed-emulator#135]
Traceback (most recent call last):
  File "mini-internet.py", line 4, in <module>
    from seedemu.layers import Base, Routing, Ebgp, Ibgp, Ospf, PeerRelationship, Dnssec
  File "/home/*/seed-emulator/seedemu/__init__.py", line 2, in <module>
    from .layers import *
  File "/home/*/seed-emulator/seedemu/layers/__init__.py", line 6, in <module>
    from .Dnssec import Dnssec
  File "/home/*/seed-emulator/seedemu/layers/Dnssec.py", line 4, in <module>
    from seedemu.services import DomainNameServer, DomainNameService
  File "/home/*/seed-emulator/seedemu/services/__init__.py", line 11, in <module>
    from .EthereumService import *
  File "/home/*/seed-emulator/seedemu/services/EthereumService/__init__.py", line 8, in <module>
    from .EthUtil import Genesis, AccountStructure, SmartContract, EthAccount
  File "/home/*/seed-emulator/seedemu/services/EthereumService/EthUtil.py", line 8, in <module>
    from web3 import Web3
ModuleNotFoundError: No module named 'web3'

**Comment by dabidgs3** [comment]
solved with pip3 install web3, but is there a way to provide the requirements?  Maybe in the README?

**Comment by kevin-w-du** [comment]
I am hoping to find an automatic way to detect this missing module. We will keep this issue open until we find a solution. Thanks.

**Comment by hunhoffe** [comment]
I installed the default version of web3 for my python/pip versions with:
```
python3 -m pip install web3
```

Now I get this error for the ethereum examples:
```
hunhoffe@node1:~/seed-emulator/examples/B06-blockchain$ ./blockchain.py
==== EthAccount: creating node_1 emulator account 0 from mnemonic...
Traceback (most recent call last):
  File "./blockchain.py", line 55, in <module>
    e1 = blockchain1.createNode("pow-eth1")
  File "/users/hunhoffe/seed-emulator/seedemu/services/EthereumService/EthereumService.py", line 281, in createNode
    return eth.installByBlockchain(vnode, self)
  File "/users/hunhoffe/seed-emulator/seedemu/services/EthereumService/EthereumService.py", line 517, in installByBlockchain
    s = self._createServer(blockchain)
  File "/users/hunhoffe/seed-emulator/seedemu/services/EthereumService/EthereumService.py", line 501, in _createServer
    return PoWServer(self.__serial, blockchain)
  File "/users/hunhoffe/seed-emulator/seedemu/services/EthereumService/EthereumServer.py", line 517, in __init__
    super().__init__(id, blockchain)
  File "/users/hunhoffe/seed-emulator/seedemu/services/EthereumService/EthereumServer.py", line 62, in __init__
    self._mnemonic_accounts = EthAccount.createEmulatorAccountsFromMnemonic(self._id, mnemonic=self._mnemonic, balance=self._account_base_balance, total=self._account_total, password="admin")
  File "/users/hunhoffe/seed-emulator/seedemu/services/EthereumService/EthUtil.py", line 201, in createEmulatorAccountsFromMnemonic
    accounts.append(EthAccount.createEmulatorAccountFromMnemonic(id, mnemonic, balance, index, password))
  File "/users/hunhoffe/seed-emulator/seedemu/services/EthereumService/EthUtil.py", line 188, in createEmulatorAccountFromMnemonic
    address = Web3.toChecksumAddress(acct.address)
AttributeError: type object 'Web3' has no attribute 'toChecksumAddress'
```
I tried updating pip & web3 but I still got the same error. I am using python version 3.8.10.
Pip reports my web3 version is 6.0.0

It would be really helpful to have versioning documented, as this is a bit of a roadblock in using those examples and running the ethereum tests.

**Comment by kevin-w-du** [comment]
It turns out that web3 changed the API to `to_checksum_address`. We need to do a thorough testing on this, as some other APIs in Web3 might have also been changed. Because this version is very new, we probably need to support both APIs.

**Comment by kevin-w-du** [comment]
I have added `requirements.txt` to the `master` branch. Please use `pip3 install -r requirements.txt` to install the required module. We decide to use the older web3 version for now, as 6.0.0 is too new. We will add the 6.0.0 support in our future release.

**Comment by hunhoffe** [comment]
Thank you, this is very helpful!
