### ISSUE TITLE
error in B06-blockchain/blockchain.py

### ISSUE THREAD

**Issue by Varie-wtx** [seed-labs/seed-emulator#145]
$ ./blockchain.py
Traceback (most recent call last):
  File "./blockchain.py", line 55, in <module>
    e1 = blockchain1.createNode("pow-eth1")
  File "/home/ht2/seed-emulator-master/seedemu/services/EthereumService/EthereumService.py", line 285, in createNode
    return eth.installByBlockchain(vnode, self)
  File "/home/ht2/seed-emulator-master/seedemu/services/EthereumService/EthereumService.py", line 519, in installByBlockchain
    if vnode in self._pending_targets.keys(): return self._pending_targets[vnode]
AttributeError: 'EthereumService' object has no attribute '_pending_targets'

Do I need to modify 'EthereumService.py'?

**Comment by Varie-wtx** [comment]
The new version(v1.0) solved this problem. Installed web3 and eth_account with pip.
