### ISSUE TITLE
Scion python version requirements

### ISSUE THREAD

**Issue by wonkr** [seed-labs/seed-emulator#157]
@lschulz , 
Is there a specific python version requirement in SCION? 

When I run the `./test/run-tests.py` with python3.8.10, it returns errors like below. But it runs well with python3.11.5. 

```
python3 run-tests.py 
Traceback (most recent call last):
  File "run-tests.py", line 5, in <module>
    from scion import ScionBgpMixedTestCase, ScionBwtesterTestCase
  File "/home/won/seed-emulator/test/scion/__init__.py", line 1, in <module>
    from .ScionTestCase import ScionTestCase
  File "/home/won/seed-emulator/test/scion/ScionTestCase.py", line 7, in <module>
    class ScionTestCase(SeedEmuTestCase):
  File "/home/won/seed-emulator/test/scion/ScionTestCase.py", line 37, in ScionTestCase
    ) -> bool | Tuple[bool, List]:
TypeError: unsupported operand type(s) for |: 'type' and '_GenericAlias'
```

**Comment by wonkr** [comment]
@lschulz  Thanks for the code update! I will run tests again with the newly updated code.

**Comment by wonkr** [comment]
I was able to run the test code without any issue after the code update.
The issue has been fixed and I am closing the this issue. 
Thanks.
